### ISSUE TITLE
Consumer运行久了出现错误fwrite(): send of 35 bytes failed

### ISSUE THREAD

**Issue by stonegithubs** [ikilobyte/pulsar-client-php#1]
Consumer运行久了出现错误fwrite(): send of 35 bytes failed，这个错误是什么原因引起的呢？
Array
(
    [message] => error
    [file] => /opt/pulsar/vendor/ikilobyte/pulsar-client-php/src/IO/StreamIO.php
    [line] => 113
    [e] => fwrite(): send of 35 bytes failed with errno=32 Broken pipe
)

另外请教下几个问题，谢谢！！！

1、支持Swoole协程环境，需要在swoole环境中做特殊处理吗，用的tp-swoole，command运行Consumer

2、如何实现消息的重复删除功能，类似Python设置send_timeout_millis;
https://pulsar.apache.org/docs/concepts-messaging/
#Python Code
import pulsar
client = pulsar.Client("pulsar://localhost:6650")
producer = client.create_producer(
    "persistent://public/default/topic-1",
    producer_name="producer-1",
    `send_timeout_millis=0)

3、除了主动重试机制外，遇到特殊原因，消息没ack也没有nack，这种情况如何消息重试功能。

4、Consumer如何订阅多个topic。
import re
consumer = client.subscribe(re.compile('persistent://public/default/topic-*'), 'my-subscription')

**Comment by ikilobyte** [comment]
> Consumer大概运行了多长时间呢，pulsar的版本是多少？pulsar如何搭建的，麻烦提供一下，方便复现
1、在Swoole中运行的话，开启`SWOOLE_HOOK_SOCKETS`、`SWOOLE_HOOK_STREAM_FUNCTION`即可，一般来说配置了`SWOOLE_HOOK_ALL`就不需要配置什么了
2、`send_timeout_millis`和重复删除功能有什么关联呢？
3、会被这个Consumer一直占有，直到有做出Ack或Nack、如果这个Consumer直到断开连接时都没有Ack，会重新投递给其它的消费者，你的需求是？
4、计划下一个版本增加

**Comment by stonegithubs** [comment]
Pulsar版本号2.10.1，服务端运行稳定，没有出现问题，Consumer运行大概1天左右出现的，测试nack，让消息不断的重试

2.官网介绍的Message deduplication地址写错了
这个地址
https://pulsar.apache.org/docs/cookbooks-deduplication/#pulsar-clients
服务端开启enable message deduplication
客户端需要设置timeout 为0
Set the message timeout to 0 (namely, no timeout).

3.关于消息重试，主要是考虑在调用Consumer#ack方法前，因为代码问题导致抛异常了，代码又没有做处理，那么会导致消费者一直重试没有被确认的消息。
在JAVA客户端可以通过Pulsar提供的死信队列来实现：当Consumer消费消息时抛异常，并达到一定的重试次数，则将消息丢入死信队列，看官方文档，其他客户端还没实现死信队列功能，是不是还需要等官方的Pulsar C++ client library开发了这个功能才能用呢

**Comment by ikilobyte** [comment]
1、Consumer掉线问题已定位，下个版本修复
2、消息去重待确定是否可以支持
3、死信队列在后续版本计划支持，这个客户端不依赖C++ client library，是纯php实现的

下个版本，支持多topic订阅，修复consumer掉线

**Comment by ikilobyte** [comment]
@stonegithubs 新版已发布， v1.0.4

**Comment by stonegithubs** [comment]
这么快发布新版本，太感谢了！！！
Pulsar用起来很顺手
