### ISSUE TITLE
setDeadLetterPolicy    第三个参数为何不能自动识别当前主题的订阅者

### ISSUE THREAD

**Issue by hyperbolaa** [ikilobyte/pulsar-client-php#13]

**Comment by ikilobyte** [comment]
什么意思？有示例代码吗？

**Comment by hyperbolaa** [comment]
setDeadLetterPolicy(int $maxRedeliveryCount, string $deadLetterTopic = '', string $initialSubscriptionName = 'logic')

**Comment by ikilobyte** [comment]
默认是`logic`，你可以配置成和消费者一致

**Comment by ikilobyte** [comment]
@hyperbolaa 已经改了，下个版本发布，默认和消费者的`subscription`一致
