### ISSUE TITLE
feof(): supplied resource is not a valid stream resource

### ISSUE THREAD

**Issue by hyperbolaa** [ikilobyte/pulsar-client-php#18]
![image](https://github.com/ikilobyte/pulsar-client-php/assets/10859667/49cf4477-e195-4654-94e7-91b00e7061de)

报错位置如上：StreamIO.php    116行
感觉这个地方要try catch 一下或判断一下

**Comment by ikilobyte** [comment]
try catch之后也是要抛出异常，其实加不加都可以

**Comment by hyperbolaa** [comment]
ok
