### ISSUE TITLE
`$options->setReceiveQueueSize(16);` 是配置协议层面，并不是批量接收消息，目前没有批量接收消息

### ISSUE THREAD

**Issue by stonegithubs** [ikilobyte/pulsar-client-php#20]
`$options->setReceiveQueueSize(16);` 是配置协议层面，并不是批量接收消息，目前没有批量接收消息

_Originally posted by @ikilobyte in https://github.com/ikilobyte/pulsar-client-php/issues/15#issuecomment-1588775279_

想用hypyerf协程批量处理消息，测试只能一条条的接收，每条消息等ack确认之后才能收到下一条
```php
while (true) {
          $wg = new WaitGroup();
          for($j=0;$j<10;$j++){
              $wg->add();
              go(function () use($consumer, $wg){
                  try {
                      $message = $consumer->receive();                    
                      $consumer->ack($message);                 
                  } catch (\Throwable $e) {
                      echo 'error111: ' . $e->getMessage(), PHP_EOL;
                  } finally {
                      $wg->done();
                  }
              });
          }
          $wg->wait();
}
```

**Comment by stonegithubs** [comment]
批量处理消息用的多个进程，要是能用协程效果更高

**Comment by ikilobyte** [comment]
@stonegithubs 下个版本会实现

**Comment by stonegithubs** [comment]
> @stonegithubs v1.2.2已发布
> 
> > 生产者
> 
> ```
> $messages = [];
> for ($i = 0;$i < 10;$i++) {
>     $messages[] = json_encode([
>           'id'    => $i,
>           'now'   => date('Y-m-d H:i:s')
>     ]);
> }
> 
> // 批量发送消息
> $messageID = $producer->send($messages);
> ```
> 
> > 消费者
> 
> ```
> // 批量接收消息，会一次收到上面发生的10条消息
> $messages = $consumer->batchReceive();
> foreach ($messages as $message) {
>     // ...    
> 
>     // Ack
>     $consumer->ack($message);
> }
> ```
> 
> * 只有生产者批量发送了消息，消费者才能批量收到消息，这是Pulsar协议规定
> * 建议消费者收到一批消息后，用`Channel`派发出去给不同的协程去处理

正需要这个功能，非常感谢，还用《不循环接收消息》来批量接收，效果非常好

**Comment by ikilobyte** [comment]
好的，那就先关闭issue了
