### ISSUE TITLE
[Questions] Regarding topic related API

### ISSUE THREAD

**Issue by g41797** [ikilobyte/pulsar-client-php#25]
Hi

In my application I need:

- create/delete topic
- purge topic messages

As far as I understand pulsar-client-php does not support above mentioned operations.

My questions:
- is topic created automatically by Pulsar after connection of consumer or producer
- any idea or reference regarding possible PHP implementation of create/delete/purge

Thanks

**Comment by ikilobyte** [comment]
@g41797 Hi This looks more like an admin api
