### ISSUE TITLE
Name lookup bug

### ISSUE THREAD

**Issue by emmanuelGuiton** [ikilobyte/pulsar-client-php#28]
Hello,

We noticed a bug during the lookup of the Pulsar broker name/IP address. The bug was introduced in 1.3.1 version, the 1.3.0 version still works correctly.

The faulty result is obtained here : https://github.com/ikilobyte/pulsar-client-php/blob/v1.3.1/src/Client.php#L142
We configured the client with the address `pulsar://pulsar-broker:6650`. The broker instance is a Docker container.
A dump of the `$result` variable shows that the hostname has been changed by the localhost IP address :
```
object(Pulsar\Lookup\Result)#156 (3) {
  ["host":protected]=>
  string(9) "127.0.0.1"
  ["port":protected]=>
  int(6650)
  ["brokerServiceUrl":protected]=>
  string(14) "127.0.0.1:6650"
}
```

The bug appears in Docker containers connected to the same Docker network than the Pulsar broker.

**Comment by ikilobyte** [comment]
@emmanuelGuiton 

1. pulsar broker is standalone ?
2. I need to look at the pulsar configuration of `advertisedAddress`

**Comment by emmanuelGuiton** [comment]
@ikilobyte 
Thanks for looking at this issue.

Yes, Pulsar is running in standalone mode.
Here is the conf : `advertisedAddress=pulsar-broker`

I edited the description since we mixed up a few details : the bug appears in Docker containers that run the Pulsar PHP Client. Ubuntu OS, PHP >= 8.2
With 1.3.0 client, the `host` in `Pulsar\Lookup\Result` stays `pulsar-broker` (which correctly binds to an IP address).
With 1.3.1 client, the `host` in `Pulsar\Lookup\Result` is changed to `127.0.0.1`.

**Comment by ikilobyte** [comment]
`advertisedAddress` It should be set to the host's ip address

v1.3.1 https://github.com/ikilobyte/pulsar-client-php/commit/18969681ac26128e23d3c77377f5eceadb0802c6 fix lookup

**Comment by emmanuelGuiton** [comment]
The documentation says `Hostname or IP address`
https://pulsar.apache.org/reference/#/3.2.x/config/reference-configuration-broker?id=advertisedaddress

I try setting the IP address instead of the hostname as a workaround. Unfortunately, in any case it does not solve the issue.

**Comment by ikilobyte** [comment]
- I need to see php run the container `ping pulsar-broker`  result 
- edit `advertisedAddress=pulsar-broker container ip address`

Or send me a copy of the detailed configuration file and I will test it.

**Comment by emmanuelGuiton** [comment]
In the end, we found out the issue : it is not the `advertisedAddress` parameter. Using the hostname here is OK.
We had a faulty configuration in the `advertisedListeners` parameter which was not empty - but should have. There was the troublesome `localhost` value.

Sorry for the inconvenience, I close this issue.
Thanks for your help.

**Comment by emmanuelGuiton** [comment]
In fact, we would indeed need to specify several listeners in Pulsar configuration (`advertisedListeners` parameter) and be able to specify the one we need in the client configuration.
Is that possible ? (I have not seen a way to configure the client with a specific listener.)

**Comment by ikilobyte** [comment]
The current version does not yet support `advertisedListeners` parameter，There are plans to support it in the next version

**Comment by emmanuelGuiton** [comment]
OK thank you. I hope I'll find a work around, then.

By the way : there is a small fix that could have helped us understanding quicker what was happening. The test here https://github.com/ikilobyte/pulsar-client-php/blob/v1.3.2/src/IO/StreamIO.php#L114 is useless since the `stream_socket_client` never return `null` (here https://github.com/ikilobyte/pulsar-client-php/blob/v1.3.2/src/IO/StreamIO.php#L87).
It returns `false` in case of failure. So the test could be :
```
if (false === $socket) {
    throw new \RuntimeException("Failed to connect to server at $address");
} else {
    $this->socket = $socket;
}
```
straight after calling `stream_socket_client` in the `connect()` function.

**Comment by ikilobyte** [comment]
Thanks for the correction, you are right, I have submitted a fix code now, you can pull it.

```bash
composer require ikilobyte/pulsar-client-php:dev-main

**Comment by ikilobyte** [comment]
@emmanuelGuiton Hi
- I wonder if pulsar broker and php are in different containers?
- Is their network communication normal?
- Please provide a complete copy `standalone.conf`
- `advertisedListeners` I don't understand the use yet, I would like to know Thank

**Comment by emmanuelGuiton** [comment]
Oh, I said something wrong again : we are not using a standalone Pulsar instance but a broker with separate instances for bookie and zookeeper. Each running in a Docker container. It does not change anything to our issue, though.

Regarding the use of the PHP client, we have a mixed situation :
- inside the Docker network : 2 custom PHP daemon applications are running themselves in Docker containers.
- outside the Docker network (using port mapping) : automated PHP tests are run on the Docker host (our workstations)

That is exactly the use case for 'advertised listeners' : https://pulsar.apache.org/docs/next/concepts-multiple-advertised-listeners/
> To ensure clients in both internal and external networks can connect to a Pulsar cluster

When supported, each instance of the Pulsar client can choose its endpoint using one of the advertised listeners name. Each listener has a different address. In our case : `pulsar://pulsar-broker:6650` (inside the Docker network) and `pulsar://localhost:6651` (outside the Docker network, mapping the `6650` port of the Pulsar broker to the `6651` port of the Docker host).

Hope it is clearer. Regarding the configuration file, we basically use the default configuration and the two following settings :
```
advertisedListeners=internal:pulsar://pulsar-broker:6650,external:pulsar://127.0.0.1:6651
internalListenerName=internal
```
