### ISSUE TITLE
TLS options 

### ISSUE THREAD

**Issue by jusstinas** [ikilobyte/pulsar-client-php#29]
At the moment if DSN is `pulsar+ssl://` or `https://`  TLS options for consumer is mandatory and without them consumer throwing exception even in general connection is possible without certs. 
Can TLS config/usage be optional?

**Comment by ikilobyte** [comment]
@jusstinas  If it's `pulsar://` or `http://` TLS options not required

**Comment by jusstinas** [comment]
Let's say I have outside test Pulsar cluster, which accepts only https connections. I need to configure consumer url as `pulsar+ssl` or `https:// ` and then TLS options are required. 
But in general it's possible to connect pulsar without certs and it's forced to do only by client. 
For example it's not mandatory in nodejs client and I guess in other clients also.

**Comment by ikilobyte** [comment]
I need to find some information and will add this feature in the next version (if possible).

**Comment by ikilobyte** [comment]
@jusstinas 

Hi, I modified the latest code in the main subsection, since I don't have your kind of requirement, so I need your help to test it, please update to the latest code

```bash
composer require ikilobyte/pulsar-client-php:dev-main
```

```TLS
$options = new \Pulsar/ConsumerOptions();
$tls = new \Pulsar\TLSOptions('','');
$options->setTLS($tls);

...
```
I'll release a new version immediately if it meets your needs, thanks!

**Comment by jusstinas** [comment]
@ikilobyte 
With those changes it's possible to connect without actual TLS config. 
Thank you!

**Comment by ikilobyte** [comment]
@jusstinas v1.3.3 release
