### ISSUE TITLE
question: are Pulsar Schema's supported?

### ISSUE THREAD

**Issue by WitteStier** [ikilobyte/pulsar-client-php#7]
Hi,

Does this client support Pulsar [Schemas](https://pulsar.apache.org/docs/2.11.x/schema-overview/) or are you planning to implement Schema support? If not, are you willing to point me in the direction so that I can implement support and contribute to the project.

**Comment by ikilobyte** [comment]
Hello, this client is currently not supported `Pulsar Schemas` , Support is planned for the next release

**Comment by WitteStier** [comment]
Hi,

Thanks for the information. Please let me know if I can help. For example with testing or development.

**Comment by ikilobyte** [comment]
@WitteStier Hello,

The schema schema has been developed but not released, can you help me test it?
Pull the master branch code if you want and see the Example code or README
